Focused Ruff

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -32,9 +32,15 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      # passing ruff linting is required
-      - name: Python - Check Linting - ruff
-        uses: astral-sh/ruff-action@v1
+      # Scoped Ruff linting
+      - name: Python - Check Linting - ruff (Scoped)
+        run: |
+          MODIFIED_FILES=$(git diff --name-only origin/HEAD | grep '\.py$')
+          if [ -n "$MODIFIED_FILES" ]; then
+            echo "$MODIFIED_FILES" | xargs ruff check --fix
+          else
+            echo "No Python files modified."
+          fi
 
       # passing pylint is not required - discuss errors in code review
       # adapted from https://github.com/davidslusser/actions_python_pylint/tree/main
@@ -44,11 +50,11 @@ jobs:
         if: always()
       - name: install pylint
         run: |
-          python -  m pip install --upgrade pip
+          python -m pip install --upgrade pip
           pip install pylint
         shell: bash
       - name: Python - Check Linting - pylint
-        run: "pylint solutions tests  || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
+        run: "pylint solutions tests || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
         shell: bash
 
   py_tests:
