update CI-Chekcs ruff and black are installed to get rid off py_formatting

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -1,4 +1,4 @@
-nname: ET CI Checks
+name: ET CI Checks
 
 on: [push, pull_request, workflow_dispatch]
 
@@ -22,21 +22,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      
-      # Check formatting with Ruff
-      - name: Python - Check Formatting with Ruff
+    
+      - name: Install Dependencies
+        run: pip install ruff black
+    
+      - name: Check Python Formatting with Ruff
         uses: astral-sh/ruff-action@v1
         with:
-          args: "--fix"  # Autofixes issues to prevent pipeline errors
+          args: "format --check"
 
-      # Check formatting with Black
-      - name: Install Black
-        run: pip install black
-        shell: bash
-      
-      - name: Check Formatting with Black
+      - name: Check Python Formatting with Black
         run: black --check .
-        shell: bash
+
 
   py_linting:
     runs-on: ubuntu-latest
@@ -44,21 +41,22 @@ jobs:
       - uses: actions/checkout@v4
 
       # passing ruff linting is required
-      - name: Python - Check Linting - Ruff
+      - name: Python - Check Linting - ruff
         uses: astral-sh/ruff-action@v1
 
       # passing pylint is not required - discuss errors in code review
-      - name: Python version
+      # adapted from https://github.com/davidslusser/actions_python_pylint/tree/main
+      - name: python version
         run: python --version
         shell: bash
         if: always()
-      - name: Install Pylint
+      - name: install pylint
         run: |
-          python -m pip install --upgrade pip
+          python -  m pip install --upgrade pip
           pip install pylint
         shell: bash
-      - name: Python - Check Linting - Pylint
-        run: "pylint solutions tests || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
+      - name: Python - Check Linting - pylint
+        run: "pylint solutions tests  || echo '::warning title=Pylint Error(s)::Discuss solutions and trade-offs in code review.'"
         shell: bash
 
   py_tests:
@@ -66,7 +64,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       
-      - name: Python version
+      - name: python version
         run: python --version
         shell: bash
       
